### ISSUE TITLE
Frame off program counter in contract of `execute`

### ISSUE THREAD

**Issue by skeuchel** [katamaran-project/katamaran#48]
The contract of the `execute` function currently [requires a points-to chunk for the program counter](https://github.com/katamaran-project/katamaran/blob/db4e3a68b65efc3d930a3e979c9cd27aeb16cf94/case_study/RiscvPmp/Contracts.v#L106) and [gives it back unmodified](https://github.com/katamaran-project/katamaran/blob/db4e3a68b65efc3d930a3e979c9cd27aeb16cf94/case_study/RiscvPmp/Contracts.v#L118). As far as I can see it is only read once in the [`step` function](https://github.com/katamaran-project/katamaran/blob/db4e3a68b65efc3d930a3e979c9cd27aeb16cf94/case_study/RiscvPmp/Machine.v#L785) and written once in the [`tick_pc` function](https://github.com/katamaran-project/katamaran/blob/db4e3a68b65efc3d930a3e979c9cd27aeb16cf94/case_study/RiscvPmp/Machine.v#L541) and in all other cases, even with things like traps, the contents of `nextpc` is used instead.

This suggests that it could be framed off from the contract of execute, which in turn would simplify the proof of the block verifier. I wonder if this is a reasonable thing to do or if some instruction of an extension might rely on having access to the `pc` register in its execute function. I hope you know more @capt-hb.

**Comment by capt-hb** [comment]
That would lead to problems. While the `pc` is only written to in `tick_pc`, it is read out in multiple locations, including in some instructions execute bodies (see for example [execute_ECALL](https://github.com/katamaran-project/katamaran/blob/2cf1cf23ee61a04773c71508a912f5f79e327a11/case_study/RiscvPmp/Machine.v#L1209), similar for `execute_MRET` and `execute_BTYPE`), as well as some helper functions in the context of traps.

**Comment by skeuchel** [comment]
It seems I overlooked that read. But it makes sense.
